require("stroiman.pluginconfig.lualine")
require("stroiman.pluginconfig.telescope-config")
require("stroiman.pluginconfig.treesitter")
require("stroiman.pluginconfig.nvim-neo-tree-config")
require("stroiman.pluginconfig.mason")
require("stroiman.pluginconfig.lsp-config")
require("stroiman.pluginconfig.none-ls")
require("stroiman.pluginconfig.cmp-config")
require("stroiman.pluginconfig.auto-session")

